media: assets

content:
  - name: writing
    label: Writing
    type: collection
    path: content/writing
    view:
      fields: [ title, author, date, draft ]
      sort: [ title, author, date, draft ]
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: lastmod, label: Last Modified, type: date}
      - {name: draft, label: Draft, type: boolean, default: true}
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          values: [ tag1, tag2, tag3]
          creatable: true
      - name: categories
        label: Categories
        type: select
        options:
          multiple: true
          values: [ cat1, cat2, cat3 ]
          creatable: true
      - {name: author, label: Author, type: string}
      - {name: description, label: Description, type: string, options: ( maxlength: 160 ) }
      - {name: body, label: Body, type: rich-text}
      - {name: showHero, label: Show Hero, type: boolean, default: true}
      - name: heroStyle
          label: Hero style
          type: select
          options:
            multiple: false
            values: [ basic, big, background, thumbAndBackground]
            creatable: false
      - {name: layoutBackgroundHeaderSpace, label: Background layout - add space below, type: boolean, default: false}
      - {name: layoutBackgroundBlur, label: Blur background hero image, type: boolean, default: true}

- name: about
    label: About
    type: file
    path: content/about.md
    fields:
      - {name: draft, label: Draft, type: boolean, default: false}
      - {name: lastmod, label: Last Modified, type: date}
      - {name: image, label: Image, type: image}
      - {name: body, label: Body, type: rich-text}
